namespace UpBrowser.Core.Css.Values;

/// <summary>Maps CSS keyword strings to IDs for fast comparison.</summary>
public enum CssValueId
{
    Invalid,
    Inherit, Initial, Unset, Revert, RevertLayer,
    Auto, None, Normal, Bold, Bolder, Lighter, Italic, Oblique,
    Underline, Overline, LineThrough, Blink,
    Solid, Double, Dotted, Dashed, Groove, Ridge, Inset, Outset, Hidden,
    Visible, Collapse,
    Scroll, Fixed, Local,
    Repeat, RepeatX, RepeatY, NoRepeat, Round, Space,
    Cover, Contain,
    Block, Inline, InlineBlock, Flex, InlineFlex, Grid, InlineGrid,
    FlowRoot, Table, InlineTable, TableRow, TableCell, TableColumn,
    TableColumnGroup, TableHeaderGroup, TableFooterGroup, TableRowGroup,
    TableCaption, Ruby, RubyBase, RubyText, RubyAnnotation,
    Relative, Absolute, Sticky, Static,
    Left, Right, Top, Bottom, Center, Middle,
    Start, End, SelfStart, SelfEnd, Baseline, FirstBaseline, LastBaseline,
    Stretch, FlexStart, FlexEnd, SpaceBetween, SpaceAround, SpaceEvenly,
    Row, RowReverse, Column, ColumnReverse, Wrap, WrapReverse, Nowrap,
    Ltr, Rtl,
    Serif, SansSerif, Monospace, Cursive, Fantasy,
    Thin, ExtraLight, Light, Medium, SemiBold, ExtraBold, Black,
    SmallCaps, AllSmallCaps, PetiteCaps, AllPetiteCaps, TitlingCaps, Unicase,
    Sub, Super, TextTop, TextBottom,
    Pre, PreLine, PreWrap, BreakSpaces,
    BreakWord, BreakAll, KeepAll,
    Clip, Ellipsis,
    Smooth, Instant,
    Always, Manual,
    Painted, Stroke, Fill,
    BoundingBox, ContentBox, PaddingBox, BorderBox, StrokeBox, FillBox, ViewBox,
    VisibleStroke, VisibleFill, VisiblePainted,
    NonZero, EvenOdd,
    Default, Pointer, Crosshair, Text, Wait, Help,
    Grab, Grabbing, Move, NotAllowed, ZoomIn, ZoomOut,
    ColResize, RowResize, EastResize, NorthResize, NorthEastResize, NorthWestResize,
    SouthResize, SouthEastResize, SouthWestResize, WestResize,
    Cell, ContextMenu, Copy, NoDrop, VerticalText, Alias, AllScroll,
    ScaleDown,
    Loose, Strict,
    Inner, Outer,
    Separate,
    TopV, BottomV, MiddleV, BaselineV,
    Inside, Outside,
    Disc, Circle, Square, Decimal, DecimalLeadingZero, LowerRoman, UpperRoman,
    LowerAlpha, UpperAlpha, LowerLatin, UpperLatin, LowerGreek,
    Hiding, Showing,
    Dark, LightV,
    Multiply, Screen, Overlay, Darken, Lighten, ColorDodge, ColorBurn,
    HardLight, SoftLight, Diff, Exclusion, Hue, Saturation,
    Color, Luminosity, PlusLighter, PlusDarker,
    Isolate, IsolateOverride, Plaintext,
    Invert, Legacy,
    Sum, MathDiff, Product, Quotient, Min, Max, Clamp, MathRound, Mod, Rem,
    Infinity, NaN,
    Capitalize, Uppercase, Lowercase, FullWidth, FullSizeKana,
    MatchParent, NoMatch,
    InterCharacter, InterWord, InterIdeograph,
    Distribute, Kashida,
    Float, Omit,
    Allow, Force,
    MarginBox, BorderBoxInset, PaddingBoxInset, ContentBoxInset,
    Safe, Unsafe,
    Justify, SpaceBetweenV, SpaceAroundV, SpaceEvenlyV, StretchV,
    Paused, Running,
    Show, Hide,
    Rows, Columns,
    MaxContent, MinContent, FitContent, FillAvailable,
    Landscape, Portrait,
    Reduce, NoPreference,
    Handwriting, Type, Speech, PointerEvents,
    Active, Inactive,
    Mono, Sans, Duotone,
    BlackAndWhite, Grayscale, Sepia, Opaque,
    CjkIdeographic, Hebrew, Hiragana, HiraganaIroha, Katakana, KatakanaIroha,
    Jpan, Koren,
    SimSun, SimHei, MicrosoftYaHei, KaiTi, FangSong, YouYuan, STSong, STHeiti, STKaiti, STFangsong,
    SizeV, LayoutV, StyleV, PaintV,
    StrictV, Content,
    SvgText,
    All,
    MaxValue
}

/// <summary>Represents a CSS keyword/identifier value, mirroring Blink's CSSIdentifierValue.</summary>
public sealed class CssIdentifierValue : CssValue
{
    public CssValueId Id { get; }
    public string? RawValue { get; }

    private CssIdentifierValue(CssValueId id, string? rawValue) : base(CssClassType.Identifier)
    {
        Id = id;
        RawValue = rawValue;
    }

    public CssIdentifierValue(CssValueId id) : base(CssClassType.Identifier)
    {
        Id = id;
    }

    public static CssIdentifierValue Create(CssValueId id) => new(id);

    public override string CssText() => RawValue ?? ValueIdToString(Id);

    public override bool Equals(CssValue other) =>
        other is CssIdentifierValue v && Id == v.Id && RawValue == v.RawValue;

    public override int GetHashCode() => HashCode.Combine((int)Id, RawValue);

    public static CssValueId StringToValueId(string value) => value.ToLowerInvariant() switch
    {
        "auto" => CssValueId.Auto,
        "none" => CssValueId.None,
        "normal" => CssValueId.Normal,
        "bold" => CssValueId.Bold,
        "italic" => CssValueId.Italic,
        "oblique" => CssValueId.Oblique,
        "solid" => CssValueId.Solid,
        "double" => CssValueId.Double,
        "dotted" => CssValueId.Dotted,
        "dashed" => CssValueId.Dashed,
        "hidden" => CssValueId.Hidden,
        "visible" => CssValueId.Visible,
        "collapse" => CssValueId.Collapse,
        "inherit" => CssValueId.Inherit,
        "initial" => CssValueId.Initial,
        "unset" => CssValueId.Unset,
        "revert" => CssValueId.Revert,
        "revert-layer" => CssValueId.RevertLayer,
        "scroll" => CssValueId.Scroll,
        "fixed" => CssValueId.Fixed,
        "local" => CssValueId.Local,
        "repeat" => CssValueId.Repeat,
        "no-repeat" => CssValueId.NoRepeat,
        "round" => CssValueId.Round,
        "space" => CssValueId.Space,
        "cover" => CssValueId.Cover,
        "contain" => CssValueId.Contain,
        "block" => CssValueId.Block,
        "inline" => CssValueId.Inline,
        "inline-block" => CssValueId.InlineBlock,
        "flex" => CssValueId.Flex,
        "inline-flex" => CssValueId.InlineFlex,
        "grid" => CssValueId.Grid,
        "inline-grid" => CssValueId.InlineGrid,
        "relative" => CssValueId.Relative,
        "absolute" => CssValueId.Absolute,
        "sticky" => CssValueId.Sticky,
        "static" => CssValueId.Static,
        "left" => CssValueId.Left,
        "right" => CssValueId.Right,
        "top" => CssValueId.Top,
        "bottom" => CssValueId.Bottom,
        "center" => CssValueId.Center,
        "start" => CssValueId.Start,
        "end" => CssValueId.End,
        "stretch" => CssValueId.Stretch,
        "flex-start" => CssValueId.FlexStart,
        "flex-end" => CssValueId.FlexEnd,
        "space-between" => CssValueId.SpaceBetween,
        "space-around" => CssValueId.SpaceAround,
        "space-evenly" => CssValueId.SpaceEvenly,
        "baseline" => CssValueId.Baseline,
        "row" => CssValueId.Row,
        "row-reverse" => CssValueId.RowReverse,
        "column" => CssValueId.Column,
        "column-reverse" => CssValueId.ColumnReverse,
        "wrap" => CssValueId.Wrap,
        "wrap-reverse" => CssValueId.WrapReverse,
        "nowrap" => CssValueId.Nowrap,
        "max-content" => CssValueId.MaxContent,
        "min-content" => CssValueId.MinContent,
        "fit-content" => CssValueId.FitContent,
        "fill-available" => CssValueId.FillAvailable,
        "table" => CssValueId.Table,
        "inline-table" => CssValueId.InlineTable,
        "table-row" => CssValueId.TableRow,
        "table-cell" => CssValueId.TableCell,
        "table-column" => CssValueId.TableColumn,
        "table-caption" => CssValueId.TableCaption,
        "landscape" => CssValueId.Landscape,
        "portrait" => CssValueId.Portrait,
        "reduce" => CssValueId.Reduce,
        "no-preference" => CssValueId.NoPreference,
        "active" => CssValueId.Active,
        "inactive" => CssValueId.Inactive,
        "all" => CssValueId.All,
        "ltr" => CssValueId.Ltr,
        "rtl" => CssValueId.Rtl,
        "content" => CssValueId.Content,
        "strict" => CssValueId.StrictV,
        "pre" => CssValueId.Pre,
        "pre-line" => CssValueId.PreLine,
        "pre-wrap" => CssValueId.PreWrap,
        "break-spaces" => CssValueId.BreakSpaces,
        "clip" => CssValueId.Clip,
        "ellipsis" => CssValueId.Ellipsis,
        "break-word" => CssValueId.BreakWord,
        "break-all" => CssValueId.BreakAll,
        "keep-all" => CssValueId.KeepAll,
        "default" => CssValueId.Default,
        "pointer" => CssValueId.Pointer,
        "grab" => CssValueId.Grab,
        "grabbing" => CssValueId.Grabbing,
        "move" => CssValueId.Move,
        "crosshair" => CssValueId.Crosshair,
        "wait" => CssValueId.Wait,
        "help" => CssValueId.Help,
        "text" => CssValueId.Text,
        "not-allowed" => CssValueId.NotAllowed,
        "separate" => CssValueId.Separate,
        "scale-down" => CssValueId.ScaleDown,
        "inside" => CssValueId.Inside,
        "outside" => CssValueId.Outside,
        "disc" => CssValueId.Disc,
        "circle" => CssValueId.Circle,
        "square" => CssValueId.Square,
        "decimal" => CssValueId.Decimal,
        "lower-roman" => CssValueId.LowerRoman,
        "upper-roman" => CssValueId.UpperRoman,
        "lower-alpha" => CssValueId.LowerAlpha,
        "upper-alpha" => CssValueId.UpperAlpha,
        "multiply" => CssValueId.Multiply,
        "screen" => CssValueId.Screen,
        "overlay" => CssValueId.Overlay,
        "darken" => CssValueId.Darken,
        "lighten" => CssValueId.Lighten,
        "color-dodge" => CssValueId.ColorDodge,
        "color-burn" => CssValueId.ColorBurn,
        "hard-light" => CssValueId.HardLight,
        "soft-light" => CssValueId.SoftLight,
        "diff" => CssValueId.Diff,
        "exclusion" => CssValueId.Exclusion,
        "hue" => CssValueId.Hue,
        "saturation" => CssValueId.Saturation,
        "color" => CssValueId.Color,
        "luminosity" => CssValueId.Luminosity,
        "isolate" => CssValueId.Isolate,
        "capitalize" => CssValueId.Capitalize,
        "uppercase" => CssValueId.Uppercase,
        "lowercase" => CssValueId.Lowercase,
        "full-width" => CssValueId.FullWidth,
        "full-size-kana" => CssValueId.FullSizeKana,
        "match-parent" => CssValueId.MatchParent,
        "justify" => CssValueId.Justify,
        "paused" => CssValueId.Paused,
        "running" => CssValueId.Running,
        "show" => CssValueId.Show,
        "hide" => CssValueId.Hide,
        "rows" => CssValueId.Rows,
        "columns" => CssValueId.Columns,
        "painted" => CssValueId.Painted,
        "stroke" => CssValueId.Stroke,
        "fill" => CssValueId.Fill,
        "nonzero" => CssValueId.NonZero,
        "evenodd" => CssValueId.EvenOdd,
        "bounding-box" => CssValueId.BoundingBox,
        "content-box" => CssValueId.ContentBox,
        "padding-box" => CssValueId.PaddingBox,
        "border-box" => CssValueId.BorderBox,
        "margin-box" => CssValueId.MarginBox,
        "serif" => CssValueId.Serif,
        "sans-serif" => CssValueId.SansSerif,
        "monospace" => CssValueId.Monospace,
        "cursive" => CssValueId.Cursive,
        "fantasy" => CssValueId.Fantasy,
        "sub" => CssValueId.Sub,
        "super" => CssValueId.Super,
        "text-top" => CssValueId.TextTop,
        "text-bottom" => CssValueId.TextBottom,
        "middle" => CssValueId.Middle,
        "small-caps" => CssValueId.SmallCaps,
        "all-small-caps" => CssValueId.AllSmallCaps,
        "underline" => CssValueId.Underline,
        "overline" => CssValueId.Overline,
        "line-through" => CssValueId.LineThrough,
        "blink" => CssValueId.Blink,
        "inner" => CssValueId.Inner,
        "outer" => CssValueId.Outer,
        "svg-text" => CssValueId.SvgText,
        "legacy" => CssValueId.Legacy,
        "invert" => CssValueId.Invert,
        "isolate-override" => CssValueId.IsolateOverride,
        "plaintext" => CssValueId.Plaintext,
        _ => CssValueId.Invalid
    };

    public static string ValueIdToString(CssValueId id) => id switch
    {
        CssValueId.Auto => "auto",
        CssValueId.None => "none",
        CssValueId.Normal => "normal",
        CssValueId.Bold => "bold",
        CssValueId.Italic => "italic",
        CssValueId.Oblique => "oblique",
        CssValueId.Solid => "solid",
        CssValueId.Double => "double",
        CssValueId.Dotted => "dotted",
        CssValueId.Dashed => "dashed",
        CssValueId.Hidden => "hidden",
        CssValueId.Visible => "visible",
        CssValueId.Collapse => "collapse",
        CssValueId.Inherit => "inherit",
        CssValueId.Initial => "initial",
        CssValueId.Unset => "unset",
        CssValueId.Revert => "revert",
        CssValueId.RevertLayer => "revert-layer",
        CssValueId.Scroll => "scroll",
        CssValueId.Fixed => "fixed",
        CssValueId.Local => "local",
        CssValueId.Repeat => "repeat",
        CssValueId.NoRepeat => "no-repeat",
        CssValueId.Round => "round",
        CssValueId.Space => "space",
        CssValueId.Cover => "cover",
        CssValueId.Contain => "contain",
        CssValueId.Block => "block",
        CssValueId.Inline => "inline",
        CssValueId.InlineBlock => "inline-block",
        CssValueId.Flex => "flex",
        CssValueId.InlineFlex => "inline-flex",
        CssValueId.Grid => "grid",
        CssValueId.InlineGrid => "inline-grid",
        CssValueId.Relative => "relative",
        CssValueId.Absolute => "absolute",
        CssValueId.Sticky => "sticky",
        CssValueId.Static => "static",
        CssValueId.Left => "left",
        CssValueId.Right => "right",
        CssValueId.Top => "top",
        CssValueId.Bottom => "bottom",
        CssValueId.Center => "center",
        CssValueId.Start => "start",
        CssValueId.End => "end",
        CssValueId.Stretch => "stretch",
        CssValueId.FlexStart => "flex-start",
        CssValueId.FlexEnd => "flex-end",
        CssValueId.SpaceBetween => "space-between",
        CssValueId.SpaceAround => "space-around",
        CssValueId.SpaceEvenly => "space-evenly",
        CssValueId.Baseline => "baseline",
        CssValueId.Row => "row",
        CssValueId.RowReverse => "row-reverse",
        CssValueId.Column => "column",
        CssValueId.ColumnReverse => "column-reverse",
        CssValueId.Wrap => "wrap",
        CssValueId.WrapReverse => "wrap-reverse",
        CssValueId.Nowrap => "nowrap",
        CssValueId.MaxContent => "max-content",
        CssValueId.MinContent => "min-content",
        CssValueId.FitContent => "fit-content",
        CssValueId.FillAvailable => "fill-available",
        CssValueId.Table => "table",
        CssValueId.InlineTable => "inline-table",
        CssValueId.TableRow => "table-row",
        CssValueId.TableCell => "table-cell",
        CssValueId.TableColumn => "table-column",
        CssValueId.TableCaption => "table-caption",
        CssValueId.Landscape => "landscape",
        CssValueId.Portrait => "portrait",
        CssValueId.Reduce => "reduce",
        CssValueId.NoPreference => "no-preference",
        CssValueId.Active => "active",
        CssValueId.Inactive => "inactive",
        CssValueId.All => "all",
        CssValueId.Ltr => "ltr",
        CssValueId.Rtl => "rtl",
        CssValueId.Content => "content",
        CssValueId.StrictV => "strict",
        CssValueId.Pre => "pre",
        CssValueId.PreLine => "pre-line",
        CssValueId.PreWrap => "pre-wrap",
        CssValueId.BreakSpaces => "break-spaces",
        CssValueId.Clip => "clip",
        CssValueId.Ellipsis => "ellipsis",
        CssValueId.BreakWord => "break-word",
        CssValueId.BreakAll => "break-all",
        CssValueId.KeepAll => "keep-all",
        CssValueId.Default => "default",
        CssValueId.Pointer => "pointer",
        CssValueId.Grab => "grab",
        CssValueId.Grabbing => "grabbing",
        CssValueId.Move => "move",
        CssValueId.Crosshair => "crosshair",
        CssValueId.Wait => "wait",
        CssValueId.Help => "help",
        CssValueId.Text => "text",
        CssValueId.NotAllowed => "not-allowed",
        CssValueId.Separate => "separate",
        CssValueId.ScaleDown => "scale-down",
        CssValueId.Inside => "inside",
        CssValueId.Outside => "outside",
        CssValueId.Disc => "disc",
        CssValueId.Circle => "circle",
        CssValueId.Square => "square",
        CssValueId.Decimal => "decimal",
        CssValueId.LowerRoman => "lower-roman",
        CssValueId.UpperRoman => "upper-roman",
        CssValueId.LowerAlpha => "lower-alpha",
        CssValueId.UpperAlpha => "upper-alpha",
        CssValueId.Multiply => "multiply",
        CssValueId.Screen => "screen",
        CssValueId.Overlay => "overlay",
        CssValueId.Darken => "darken",
        CssValueId.Lighten => "lighten",
        CssValueId.ColorDodge => "color-dodge",
        CssValueId.ColorBurn => "color-burn",
        CssValueId.HardLight => "hard-light",
        CssValueId.SoftLight => "soft-light",
        CssValueId.Diff => "diff",
        CssValueId.Exclusion => "exclusion",
        CssValueId.Hue => "hue",
        CssValueId.Saturation => "saturation",
        CssValueId.Color => "color",
        CssValueId.Luminosity => "luminosity",
        CssValueId.Isolate => "isolate",
        CssValueId.Capitalize => "capitalize",
        CssValueId.Uppercase => "uppercase",
        CssValueId.Lowercase => "lowercase",
        CssValueId.Justify => "justify",
        CssValueId.Paused => "paused",
        CssValueId.Running => "running",
        CssValueId.Show => "show",
        CssValueId.Hide => "hide",
        CssValueId.Rows => "rows",
        CssValueId.Columns => "columns",
        CssValueId.Painted => "painted",
        CssValueId.Stroke => "stroke",
        CssValueId.Fill => "fill",
        CssValueId.NonZero => "nonzero",
        CssValueId.EvenOdd => "evenodd",
        CssValueId.BoundingBox => "bounding-box",
        CssValueId.ContentBox => "content-box",
        CssValueId.PaddingBox => "padding-box",
        CssValueId.BorderBox => "border-box",
        CssValueId.MarginBox => "margin-box",
        CssValueId.Serif => "serif",
        CssValueId.SansSerif => "sans-serif",
        CssValueId.Monospace => "monospace",
        CssValueId.Cursive => "cursive",
        CssValueId.Fantasy => "fantasy",
        CssValueId.Sub => "sub",
        CssValueId.Super => "super",
        CssValueId.TextTop => "text-top",
        CssValueId.TextBottom => "text-bottom",
        CssValueId.Middle => "middle",
        CssValueId.SmallCaps => "small-caps",
        CssValueId.AllSmallCaps => "all-small-caps",
        CssValueId.Underline => "underline",
        CssValueId.Overline => "overline",
        CssValueId.LineThrough => "line-through",
        CssValueId.Blink => "blink",
        CssValueId.Inner => "inner",
        CssValueId.Outer => "outer",
        CssValueId.SvgText => "svg-text",
        CssValueId.Legacy => "legacy",
        CssValueId.Invert => "invert",
        CssValueId.IsolateOverride => "isolate-override",
        CssValueId.Plaintext => "plaintext",
        CssValueId.LightV => "light",
        CssValueId.Dark => "dark",
        CssValueId.PlusLighter => "plus-lighter",
        CssValueId.PlusDarker => "plus-darker",
        CssValueId.MathRound => "round",
        CssValueId.Mod => "mod",
        CssValueId.Rem => "rem",
        _ => id.ToString().ToLowerInvariant()
    };
}