<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VC-LTL" Version="5.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UpBrowser.Core\UpBrowser.Core.csproj" />
  </ItemGroup>
</Project>
