<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="VC-LTL" Version="5.3.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalSkiaSharp)' == 'true'">
    <ProjectReference Include="..\third_party\SkiaSharp\binding\SkiaSharp\SkiaSharp.csproj" Properties="TargetFramework=net10.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalSkiaSharp)' != 'true'">
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <!--<PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="*" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UpBrowser.Native\UpBrowser.Native.csproj" />
    <ProjectReference Include="..\UpBrowser.Core\UpBrowser.Core.csproj" />
    <ProjectReference Include="..\UpBrowser.Input\UpBrowser.Input.csproj" />
  </ItemGroup>
</Project>
