<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>true</PublishAot>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <NoWarn>$(NoWarn);IL2026;IL2111</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net10.0-windows</TargetFramework>
    <SupportedOSPlatformVersion>5.1</SupportedOSPlatformVersion>
    <SupportWinXP>true</SupportWinXP>
  </PropertyGroup>
  <PropertyGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <PackageReference Include="YY-Thunks" Version="1.2.2" />
    <PackageReference Include="VC-LTL" Version="5.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\third_party\jint\Jint\Jint.csproj" />
    <ProjectReference Include="..\UpBrowser.JsEngineProtocol\UpBrowser.JsEngineProtocol.csproj" />
    <TrimmerRootAssembly Include="Jint" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DomSetup.js">
      <LogicalName>UpBrowser.JsEngineHost.DomSetup.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
