<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
 	<PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <SupportedOSPlatformVersion>5.1</SupportedOSPlatformVersion>
    <SupportWinXP>true</SupportWinXP>
  </PropertyGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <PackageReference Include="YY-Thunks" Version="1.2.2" />
    <PackageReference Include="VC-LTL" Version="5.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UpBrowser.JsEngineProtocol\UpBrowser.JsEngineProtocol.csproj" />
    <ProjectReference Include="..\UpBrowser.Core\UpBrowser.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JavaScriptEngineSwitcher.Core" Version="*" />
    <PackageReference Include="JavaScriptEngineSwitcher.Jint" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DomSetup.js">
      <LogicalName>UpBrowser.JsEngineHost.DomSetup.js</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>