<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTrimmable>false</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
    <SupportWinXP>true</SupportWinXP>
    <DefineConstants>$(DefineConstants);SUPPORT_WINXP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="$(MSBuildThisFileDirectory)ILLink.Descriptors.xml" />
  </ItemGroup>

  <Import Project="..\third_party\SkiaSharp\binding\IncludeNativeAssets.SkiaSharp.targets" Condition="'$(UseLocalSkiaSharp)' == 'true'" />

  <ItemGroup Condition="'$(UseLocalSkiaSharp)' == 'true'">
    <ProjectReference Include="..\third_party\SkiaSharp\binding\SkiaSharp\SkiaSharp.csproj" Properties="TargetFramework=net10.0-windows10.0.19041.0" />
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux')) or $(RuntimeIdentifier.Contains('linux'))">
    <UseLinuxSkiaNative>true</UseLinuxSkiaNative>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseLocalSkiaSharp)' != 'true'">
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.1" Condition="'$(UseLinuxSkiaNative)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VC-LTL" Version="5.3.1" />
    <PackageReference Include="YY-Thunks" Version="1.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UpBrowser.Platform\UpBrowser.Platform.csproj" />
    <ProjectReference Include="..\UpBrowser.Core\UpBrowser.Core.csproj" />
  </ItemGroup>
</Project>
